### ISSUE TITLE
Change colors

### ISSUE THREAD

**Issue by allthesignals** [MAPC/trailmap2#50]
> I created a new line type that I like for the combo.  Can you emulate that?  Using the same colors as below.
>  
> Greenway color (RGB)
> 214, 157, 188
>  
> Hiking Trails
> 255, 211, 127

![image](https://cloud.githubusercontent.com/assets/5004319/22604576/3f0525e0-ea1a-11e6-84a5-e4301ea51989.png)

**Comment by arouault** [comment]
Complete
