### ISSUE TITLE
CONTENT: Change labels in legend with informational text on hover

### ISSUE THREAD

**Issue by arouault** [MAPC/trailmap2#51]
Hover text in italic
Titles in bold

**Bike**
    Protected Bike Lane  _Bicycle lane that is physically separated from the travel lane_
    Bike Lane _Striped bicycle lane on the roadway_
    Shared Lane Marking _Sharrow indicating a priority bicycle route shared with motor vehicles_

**Walk**
    Foot path _Natural surface or paved path primarily for walking_

**Multi-Use Path**
    Paved  _Path is paved with a firm stable surface, typically asphalt or stone dust_
    ​Unimproved _Future paved path that is currently passable by foot_

**LandLine (Metro Greenway Network)**
    Greenway Route _Priority route for cycling and walking with priority for separation from traffic_
    Regional Foot path _Regional trail for walking, either through conservation areas, or urban trails_
    ​Combination _Greenway and foot path routes overlap in this section_

**Comment by allthesignals** [comment]
@arouault addressed & merged, please check
