### ISSUE TITLE
List Proposed Trails toggle first

### ISSUE THREAD

**Issue by arouault** [MAPC/trailmap2#52]
Reorder to have proposed trails toggle as the first in the list on the Legend

**Comment by allthesignals** [comment]
@arouault right now the legend is like this:
Trailmap Filters:
 - Bike
 - Walk
 - Multi-use path
 - LandLine
Basemaps
 - Default
 - Open Street Map
 - Satellite
 - Proposed Trails
 - Home

And we want it to be this:
Trailmap Filters:
 - Proposed Trails
 - Bike
 - Walk
 - Multi-use path
 - LandLine
Basemaps
 - Default
 - Open Street Map
 - Satellite
 - Home

Is that correct?

**Comment by arouault** [comment]
Yes except make sure you use the text from issue #51 51.

**Comment by allthesignals** [comment]
@arouault gotcha - thank you!

**Comment by allthesignals** [comment]
@arouault this has been addressed, please check, thanks
