### ISSUE TITLE
Transfer trailmap.mapc.org to current site

### ISSUE THREAD

**Issue by arouault** [MAPC/trailmap2#58]
Switchover site to old URL. Keep a file copy of the old site.

**Comment by allthesignals** [comment]
Buddy is looking into the best solution for this.

**Comment by allthesignals** [comment]
Buddy has transferred the current domain, and I've purchased the SSL certificate (which I'll need to be reimbursed on), but he's struggling to get it to work with the current setup. I've reached out to Pagefront and cc'd Buddy and @arouault to try and understand how to get it configured. 

An alternative might be to use this: https://dnsimple.com/. I would suggest this to Buddy as an alternative. 

Until SSL works, the geolocation feature will **not** work. You can force it to work by sending users to http**s**://trailmap.mapc.org, but it will create a warning.

**Comment by allthesignals** [comment]
We could move the release here to get ssh working: http://surge.sh/help/securing-your-custom-domain-with-ssl.

**Comment by allthesignals** [comment]
The site is switched over to the old URL, so this should be considered done - although some other related issues about image slowness might be related to the infrastructure behind this.
