### ISSUE TITLE
Add logos to bottom of Legend

### ISSUE THREAD

**Issue by arouault** [MAPC/trailmap2#60]
1) MAPC
![mapclogo](https://cloud.githubusercontent.com/assets/1305629/25868539/07cdff56-34cb-11e7-8522-a9116a12c0a6.png)

with link to mapc.org

and 

2) Landline 

![landline_logo-combined](https://cloud.githubusercontent.com/assets/1305629/25873294/f3d6a3ca-34db-11e7-98bc-328b52ddc97d.png)

Please resize to fit the legend and place on a grid

**Comment by allthesignals** [comment]
@arouault FYI the second logo is not transparent.
